export const BlackCards = [
  {
    "id": "EB01-040",
    "name": "Kyros",
    "category": "LEADER",
    "color": "Black/Yellow",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/EB01-040.png?240725",
    "effect": "[Activate: Main] [Once Per Turn] You may turn 1 card from the top of your Life cards face-up: K.O. up to 1 of your opponent's Characters with a cost of 0.",
    "type": "Dressrosa",
    "cost": "4",
    "atribbute": "Slash"
  },
  {
    "id": "EB01-041",
    "name": "Crocus",
    "category": "CHARACTER",
    "color": "Black",
    "power": "8000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/EB01-041.png?240725",
    "effect": "-",
    "type": "Former Roger Pirates",
    "cost": "6",
    "atribbute": "Wisdom"
  },
  {
    "id": "EB01-042",
    "name": "Scarlet",
    "category": "CHARACTER",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/EB01-042.png?240725",
    "effect": "[Activate: Main] You may trash this Character: Play up to 1 {Dressrosa} type Character card with a cost of 3 or less other than [Scarlet] from your hand rested. Then, give up to 1 of your opponent's Characters −2 cost during this turn.",
    "type": "Dressrosa",
    "cost": "2",
    "atribbute": "Wisdom"
  },
  {
    "id": "EB01-043",
    "name": "Spandine",
    "category": "CHARACTER",
    "color": "Black",
    "power": "2000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/EB01-043.png?240725",
    "effect": "[On Play] You may place 3 cards with a type including \"CP\" from your trash at the bottom of your deck in any order: Play up to 1 Character card with a type including \"CP\" and a cost of 4 or less other than [Spandine] from your trash rested.",
    "type": "CP9",
    "cost": "3",
    "atribbute": "Wisdom"
  },
  {
    "id": "EB01-044",
    "name": "Funkfreed",
    "category": "CHARACTER",
    "color": "Black",
    "power": "1000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/EB01-044.png?240725",
    "effect": "[Activate: Main] You may rest this Character: Up to 1 of your [Spandam] Characters gains +3000 power during this turn.",
    "type": "CP9",
    "cost": "1",
    "atribbute": "Slash"
  },
  {
    "id": "EB01-045",
    "name": "Brook",
    "category": "CHARACTER",
    "color": "Black",
    "power": "4000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/EB01-045.png?240725",
    "effect": "[On Play] If your opponent has a Character with a cost of 0, this Character gains [Rush] during this turn.(This card can attack on the turn in which it is played.)",
    "type": "Rumbar Pirates",
    "cost": "3",
    "atribbute": "Slash"
  },
  {
    "id": "EB01-046",
    "name": "Brook",
    "category": "CHARACTER",
    "color": "Black",
    "power": "4000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/EB01-046.png?240725",
    "effect": "[On Play]/[When Attacking] Give up to 1 of your opponent's Characters −1 cost during this turn. Then, K.O. up to 1 of your opponent's Characters with a cost of 0.",
    "type": "Straw Hat Crew",
    "cost": "3",
    "atribbute": "Slash"
  },
  {
    "id": "EB01-047",
    "name": "Laboon",
    "category": "CHARACTER",
    "color": "Black",
    "power": "4000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/EB01-047.png?240725",
    "effect": "[Once Per Turn] When a Character is K.O.'d, draw 1 card and trash 1 card from your hand.",
    "type": "Animal",
    "cost": "2",
    "atribbute": "Strike"
  },
  {
    "id": "EB01-048",
    "name": "Laboon",
    "category": "CHARACTER",
    "color": "Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/EB01-048.png?240725",
    "effect": "[Activate: Main] You may rest this Character: Give up to 1 of your opponent's Characters −4 cost during this turn.",
    "type": "Animal",
    "cost": "4",
    "atribbute": "Strike"
  },
  {
    "id": "EB01-049",
    "name": "T-Bone",
    "category": "CHARACTER",
    "color": "Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/EB01-049.png?240725",
    "effect": "[On Play] K.O. up to 1 of your opponent's Characters with a cost of 2 or less.",
    "type": "Water Seven/Navy",
    "cost": "5",
    "atribbute": "Slash"
  },
  {
    "id": "EB01-050",
    "name": "...I Want to Live!!",
    "category": "EVENT",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/EB01-050.png?240725",
    "effect": "[Counter] If you have 30 or more cards in your trash, add up to 1 card from the top of your deck to the top of your Life cards.",
    "type": "Straw Hat Crew",
    "cost": "3",
    "atribbute": ""
  },
  {
    "id": "EB01-051",
    "name": "Finger Pistol",
    "category": "EVENT",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/EB01-051.png?240725",
    "effect": "[Main] You may trash 2 cards from the top of your deck: K.O. up to 1 of your opponent's Characters with a cost of 5 or less.",
    "type": "CP9",
    "cost": "4",
    "atribbute": ""
  },
  {
    "id": "OP02-002",
    "name": "Monkey.D.Garp",
    "category": "LEADER",
    "color": "Red/Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-002.png?240725",
    "effect": "[Your Turn] When this Leader or any of your Characters is given a DON!! card, give up to 1 of your opponent's Characters with a cost of 7 or less −1 cost during this turn.",
    "type": "Navy",
    "cost": "4",
    "atribbute": "Strike"
  },
  {
    "id": "OP02-072",
    "name": "Zephyr",
    "category": "LEADER",
    "color": "Purple/Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-072.png?240725",
    "effect": "[When Attacking] DON!! −4 (You may return the specified number of DON!! cards from your field to your DON!! deck.): K.O. up to 1 of your opponent's Characters with a cost of 3 or less. Then, this Leader gains +1000 power during this turn.",
    "type": "FILM/Neo Navy",
    "cost": "4",
    "atribbute": "Strike"
  },
  {
    "id": "OP02-093",
    "name": "Smoker",
    "category": "LEADER",
    "color": "Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-093.png?240725",
    "effect": "[DON!! x1] [Activate: Main] [Once Per Turn] Give up to 1 of your opponent's Characters −1 cost during this turn. Then, if there is a Character with a cost of 0, this Leader gains +1000 power during this turn.",
    "type": "Navy",
    "cost": "5",
    "atribbute": "Special"
  },
  {
    "id": "OP02-094",
    "name": "Isuka",
    "category": "CHARACTER",
    "color": "Black",
    "power": "4000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-094.png?240725",
    "effect": "[DON!! x1] [Once Per Turn] When this Character battles and K.O.'s your opponent's Character, set this Character as active.",
    "type": "Navy",
    "cost": "3",
    "atribbute": "Slash"
  },
  {
    "id": "OP02-095",
    "name": "Onigumo",
    "category": "CHARACTER",
    "color": "Black",
    "power": "6000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-095.png?240725",
    "effect": "If there is a Character with a cost of 0, this Character gains [Banish].(When this card deals damage, the target card is trashed without activating its Trigger.)",
    "type": "Navy",
    "cost": "5",
    "atribbute": "Slash"
  },
  {
    "id": "OP02-096",
    "name": "Kuzan",
    "category": "CHARACTER",
    "color": "Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-096.png?240725",
    "effect": "[On Play] Draw 1 card.[When Attacking] Give up to 1 of your opponent's Characters −4 cost during this turn.",
    "type": "Navy",
    "cost": "4",
    "atribbute": "Special"
  },
  {
    "id": "OP02-097",
    "name": "Komille",
    "category": "CHARACTER",
    "color": "Black",
    "power": "3000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-097.png?240725",
    "effect": "-",
    "type": "Navy",
    "cost": "1",
    "atribbute": "Slash"
  },
  {
    "id": "OP02-098",
    "name": "Koby",
    "category": "CHARACTER",
    "color": "Black",
    "power": "4000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-098.png?240725",
    "effect": "[On Play] You may trash 1 card from your hand: K.O. up to 1 of your opponent's Characters with a cost of 3 or less.",
    "type": "Navy",
    "cost": "3",
    "atribbute": "Strike"
  },
  {
    "id": "OP02-099",
    "name": "Sakazuki",
    "category": "CHARACTER",
    "color": "Black",
    "power": "7000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-099.png?240725",
    "effect": "[On Play] You may trash 1 card from your hand: K.O. up to 1 of your opponent's Characters with a cost of 5 or less.",
    "type": "Navy",
    "cost": "6",
    "atribbute": "Special"
  },
  {
    "id": "OP02-100",
    "name": "Jango",
    "category": "CHARACTER",
    "color": "Black",
    "power": "3000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-100.png?240725",
    "effect": "If you have [Fullbody], this Character cannot be K.O.'d in battle.",
    "type": "Navy",
    "cost": "2",
    "atribbute": "Slash"
  },
  {
    "id": "OP02-101",
    "name": "Strawberry",
    "category": "CHARACTER",
    "color": "Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-101.png?240725",
    "effect": "[When Attacking] If there is a Character with a cost of 0, your opponent cannot activate the [Blocker] of any Character with a cost of 5 or less during this battle.",
    "type": "Navy",
    "cost": "4",
    "atribbute": "Slash"
  },
  {
    "id": "OP02-102",
    "name": "Smoker",
    "category": "CHARACTER",
    "color": "Black",
    "power": "4000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-102.png?240725",
    "effect": "This Character cannot be K.O.'d by effects.[When Attacking] If there is a Character with a cost of 0, this Character gains +2000 power during this battle.",
    "type": "Navy",
    "cost": "3",
    "atribbute": "Special"
  },
  {
    "id": "OP02-103",
    "name": "Sengoku",
    "category": "CHARACTER",
    "color": "Black",
    "power": "3000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-103.png?240725",
    "effect": "[DON!! x1] [When Attacking] Give up to 1 of your opponent's Characters −2 cost during this turn.",
    "type": "Navy",
    "cost": "2",
    "atribbute": "Wisdom"
  },
  {
    "id": "OP02-104",
    "name": "Sentomaru",
    "category": "CHARACTER",
    "color": "Black",
    "power": "3000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-104.png?240725",
    "effect": "-",
    "type": "Navy",
    "cost": "2",
    "atribbute": "Slash"
  },
  {
    "id": "OP02-105",
    "name": "Tashigi",
    "category": "CHARACTER",
    "color": "Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-105.png?240725",
    "effect": "[DON!! x1] [When Attacking] Give up to 1 of your opponent's Characters −3 cost during this turn.",
    "type": "Navy",
    "cost": "3",
    "atribbute": "Slash"
  },
  {
    "id": "OP02-106",
    "name": "Tsuru",
    "category": "CHARACTER",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-106.png?240725",
    "effect": "[On Play] Give up to 1 of your opponent's Characters −2 cost during this turn.",
    "type": "Navy",
    "cost": "1",
    "atribbute": "Wisdom"
  },
  {
    "id": "OP02-107",
    "name": "Doberman",
    "category": "CHARACTER",
    "color": "Black",
    "power": "4000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-107.png?240725",
    "effect": "-",
    "type": "Navy",
    "cost": "2",
    "atribbute": "Strike"
  },
  {
    "id": "OP02-108",
    "name": "Donquixote Rosinante",
    "category": "CHARACTER",
    "color": "Black",
    "power": "2000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-108.png?240725",
    "effect": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)",
    "type": "Navy/Donquixote Pirates",
    "cost": "2",
    "atribbute": "Special"
  },
  {
    "id": "OP02-109",
    "name": "Jaguar.D.Saul",
    "category": "CHARACTER",
    "color": "Black",
    "power": "6000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-109.png?240725",
    "effect": "-",
    "type": "Giant/Navy",
    "cost": "4",
    "atribbute": "Strike"
  },
  {
    "id": "OP02-110",
    "name": "Hina",
    "category": "CHARACTER",
    "color": "Black",
    "power": "6000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-110.png?240725",
    "effect": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)[On Block] Select up to 1 of your opponent's Characters with a cost of 6 or less. The selected Character cannot attack during this turn.",
    "type": "Navy",
    "cost": "5",
    "atribbute": "Special"
  },
  {
    "id": "OP02-111",
    "name": "Fullbody",
    "category": "CHARACTER",
    "color": "Black",
    "power": "3000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-111.png?240725",
    "effect": "[When Attacking] If you have [Jango], this card gains +3000 power during this battle.",
    "type": "Navy",
    "cost": "2",
    "atribbute": "Strike"
  },
  {
    "id": "OP02-112",
    "name": "Bell-mère",
    "category": "CHARACTER",
    "color": "Black",
    "power": "1000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-112.png?240725",
    "effect": "[Activate: Main] You may rest this Character: Give up to 1 of your opponent's Characters −1 cost during this turn. Then, up to 1 of your Leader or Character cards gains +1000 power during this turn.",
    "type": "Navy",
    "cost": "1",
    "atribbute": "Ranged"
  },
  {
    "id": "OP02-113",
    "name": "Helmeppo",
    "category": "CHARACTER",
    "color": "Black",
    "power": "3000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-113.png?240725",
    "effect": "[When Attacking] Give up to 1 of your opponent's Characters −2 cost during this turn. Then, if there is a Character with a cost of 0, this Character gains +2000 power during this battle.",
    "type": "Navy",
    "cost": "3",
    "atribbute": "Slash"
  },
  {
    "id": "OP02-114",
    "name": "Borsalino",
    "category": "CHARACTER",
    "color": "Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-114.png?240725",
    "effect": "[Opponent's Turn] This Character gains +1000 power and cannot be K.O.'d by effects.[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)",
    "type": "Navy",
    "cost": "4",
    "atribbute": "Special"
  },
  {
    "id": "OP02-115",
    "name": "Monkey.D.Garp",
    "category": "CHARACTER",
    "color": "Black",
    "power": "3000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-115.png?240725",
    "effect": "[DON!! x2] [When Attacking] K.O. up to 1 of your opponent's Characters with a cost of 0.",
    "type": "Navy",
    "cost": "2",
    "atribbute": "Strike"
  },
  {
    "id": "OP02-116",
    "name": "Yamakaji",
    "category": "CHARACTER",
    "color": "Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-116.png?240725",
    "effect": "-",
    "type": "Navy",
    "cost": "3",
    "atribbute": "Slash"
  },
  {
    "id": "OP02-117",
    "name": "Ice Age",
    "category": "EVENT",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-117.png?240725",
    "effect": "[Main] Give up to 1 of your opponent's Characters −5 cost during this turn.",
    "type": "Navy",
    "cost": "1",
    "atribbute": ""
  },
  {
    "id": "OP02-118",
    "name": "Yasakani Sacred Jewel",
    "category": "EVENT",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-118.png?240725",
    "effect": "[Counter] You may trash 1 card from your hand: Select up to 1 of your Characters. The selected Character cannot be K.O.'d during this battle.",
    "type": "Navy",
    "cost": "1",
    "atribbute": ""
  },
  {
    "id": "OP02-119",
    "name": "Meteor Volcano",
    "category": "EVENT",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-119.png?240725",
    "effect": "[Main] K.O. up to 1 of your opponent's Characters with a cost of 1 or less.",
    "type": "Navy",
    "cost": "2",
    "atribbute": ""
  },
  {
    "id": "OP02-121",
    "name": "Kuzan",
    "category": "CHARACTER",
    "color": "Black",
    "power": "10000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-121.png?240725",
    "effect": "[Your Turn] Give all of your opponent's Characters −5 cost.[On Play] K.O. up to 1 of your opponent's Characters with a cost of 0.",
    "type": "Former Navy",
    "cost": "10",
    "atribbute": "Special"
  },
  {
    "id": "OP03-076",
    "name": "Rob Lucci",
    "category": "LEADER",
    "color": "Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP03-076.png?240725",
    "effect": "[Your Turn] [Once Per Turn] You may trash 2 cards from your hand: When your opponent's Character is K.O.'d, set this Leader as active.",
    "type": "CP9",
    "cost": "5",
    "atribbute": "Strike"
  },
  {
    "id": "OP03-077",
    "name": "Charlotte Linlin",
    "category": "LEADER",
    "color": "Black/Yellow",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP03-077.png?240725",
    "effect": "[DON!! x2] [When Attacking] ② (You may rest the specified number of DON!! cards in your cost area.) You may trash 1 card from your hand: If you have 1 or less Life cards, add up to 1 card from the top of your deck to the top of your Life cards.",
    "type": "The Four Emperors/Big Mom Pirates",
    "cost": "4",
    "atribbute": "Special"
  },
  {
    "id": "OP03-078",
    "name": "Issho",
    "category": "CHARACTER",
    "color": "Black",
    "power": "9000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP03-078.png?240725",
    "effect": "[DON!! x1] [Your Turn] Give all of your opponent's Characters −3 cost.[On Play] If your opponent has 6 or more cards in their hand, trash 2 cards from your opponent's hand.",
    "type": "Navy",
    "cost": "8",
    "atribbute": "Slash"
  },
  {
    "id": "OP03-079",
    "name": "Vergo",
    "category": "CHARACTER",
    "color": "Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP03-079.png?240725",
    "effect": "[DON!! x1] This Character cannot be K.O.'d in battle.",
    "type": "Navy/Donquixote Pirates",
    "cost": "5",
    "atribbute": "Strike"
  },
  {
    "id": "OP03-080",
    "name": "Kaku",
    "category": "CHARACTER",
    "color": "Black",
    "power": "6000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP03-080.png?240725",
    "effect": "[On Play] You may place 2 cards with a type including \"CP\" from your trash at the bottom of your deck in any order: K.O. up to 1 of your opponent's Characters with a cost of 3 or less.",
    "type": "CP9",
    "cost": "5",
    "atribbute": "Slash"
  },
  {
    "id": "OP03-081",
    "name": "Kalifa",
    "category": "CHARACTER",
    "color": "Black",
    "power": "4000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP03-081.png?240725",
    "effect": "[On Play] Draw 2 cards and trash 2 cards from your hand. Then, give up to 1 of your opponent's Characters −2 cost during this turn.",
    "type": "CP9",
    "cost": "4",
    "atribbute": "Special"
  },
  {
    "id": "OP03-082",
    "name": "Kumadori",
    "category": "CHARACTER",
    "color": "Black",
    "power": "6000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP03-082.png?240725",
    "effect": "-",
    "type": "CP9",
    "cost": "4",
    "atribbute": "Strike"
  },
  {
    "id": "OP03-083",
    "name": "Corgy",
    "category": "CHARACTER",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP03-083.png?240725",
    "effect": "[On Play] Look at 5 cards from the top of your deck and trash up to 2 cards. Then, place the rest at the bottom of your deck in any order.",
    "type": "World Government",
    "cost": "1",
    "atribbute": "Wisdom"
  },
  {
    "id": "OP03-084",
    "name": "Jerry",
    "category": "CHARACTER",
    "color": "Black",
    "power": "4000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP03-084.png?240725",
    "effect": "-",
    "type": "CP6",
    "cost": "2",
    "atribbute": "Strike"
  },
  {
    "id": "OP03-085",
    "name": "Jabra",
    "category": "CHARACTER",
    "color": "Black",
    "power": "7000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP03-085.png?240725",
    "effect": "-",
    "type": "CP9",
    "cost": "5",
    "atribbute": "Strike"
  },
  {
    "id": "OP03-086",
    "name": "Spandam",
    "category": "CHARACTER",
    "color": "Black",
    "power": "2000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP03-086.png?240725",
    "effect": "[On Play] If your Leader's type includes \"CP\", look at 3 cards from the top of your deck; reveal up to 1 card with a type including \"CP\" other than [Spandam] and add it to your hand. Then, trash the rest.",
    "type": "CP9",
    "cost": "1",
    "atribbute": "Slash"
  },
  {
    "id": "OP03-087",
    "name": "Nero",
    "category": "CHARACTER",
    "color": "Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP03-087.png?240725",
    "effect": "-",
    "type": "CP9",
    "cost": "3",
    "atribbute": "Ranged"
  },
  {
    "id": "OP03-088",
    "name": "Fukurou",
    "category": "CHARACTER",
    "color": "Black",
    "power": "3000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP03-088.png?240725",
    "effect": "This Character cannot be K.O.'d by effects.[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)",
    "type": "CP9",
    "cost": "3",
    "atribbute": "Strike"
  },
  {
    "id": "OP03-089",
    "name": "Brannew",
    "category": "CHARACTER",
    "color": "Black",
    "power": "3000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP03-089.png?240725",
    "effect": "[On Play] Look at 3 cards from the top of your deck; reveal up to 1 {Navy} type card other than [Brannew] and add it to your hand. Then, trash the rest.",
    "type": "Navy",
    "cost": "2",
    "atribbute": "Wisdom"
  },
  {
    "id": "OP03-090",
    "name": "Blueno",
    "category": "CHARACTER",
    "color": "Black",
    "power": "6000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP03-090.png?240725",
    "effect": "[DON!! x1] This Character gains [Blocker].(After your opponent declares an attack, you may rest this card to make it the new target of the attack.)[On K.O.] Play up to 1 Character card with a type including \"CP\" and a cost of 4 or less from your trash rested.",
    "type": "CP9",
    "cost": "5",
    "atribbute": "Strike"
  },
  {
    "id": "OP03-091",
    "name": "Helmeppo",
    "category": "CHARACTER",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP03-091.png?240725",
    "effect": "[On Play] Set the cost of up to 1 of your opponent's Characters with no base effect to 0 during this turn.",
    "type": "Navy",
    "cost": "1",
    "atribbute": "Wisdom"
  },
  {
    "id": "OP03-092",
    "name": "Rob Lucci",
    "category": "CHARACTER",
    "color": "Black",
    "power": "7000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP03-092.png?240725",
    "effect": "[On Play] You may place 2 cards with a type including \"CP\" from your trash at the bottom of your deck in any order: This Character gains [Rush] during this turn.(This card can attack on the turn in which it is played.)",
    "type": "CP9",
    "cost": "6",
    "atribbute": "Strike"
  },
  {
    "id": "OP03-093",
    "name": "Wanze",
    "category": "CHARACTER",
    "color": "Black",
    "power": "4000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP03-093.png?240725",
    "effect": "[On Play] You may trash 1 card from your hand: If your Leader's type includes \"CP\", K.O. up to 1 of your opponent's Characters with a cost of 1 or less.",
    "type": "CP7",
    "cost": "2",
    "atribbute": "Slash"
  },
  {
    "id": "OP03-094",
    "name": "Air Door",
    "category": "EVENT",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP03-094.png?240725",
    "effect": "[Main] If your Leader's type includes \"CP\", look at 5 cards from the top of your deck; play up to 1 Character card with a type including \"CP\" and a cost of 5 or less. Then, trash the rest.",
    "type": "CP9",
    "cost": "4",
    "atribbute": ""
  },
  {
    "id": "OP03-095",
    "name": "Soap Sheep",
    "category": "EVENT",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP03-095.png?240725",
    "effect": "[Main] Give up to 2 of your opponent's Characters −2 cost during this turn.",
    "type": "CP9",
    "cost": "1",
    "atribbute": ""
  },
  {
    "id": "OP03-096",
    "name": "Tempest Kick Sky Slicer",
    "category": "EVENT",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP03-096.png?240725",
    "effect": "[Main] K.O. up to 1 of your opponent's Characters with a cost of 0 or your opponent's Stages with a cost of 3 or less.",
    "type": "CP9",
    "cost": "2",
    "atribbute": ""
  },
  {
    "id": "OP03-097",
    "name": "Six King Pistol",
    "category": "EVENT",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP03-097.png?240725",
    "effect": "[Counter] You may trash 1 card from your hand: Up to 1 of your Leader or Character cards gains +3000 power during this battle.",
    "type": "CP9",
    "cost": "-",
    "atribbute": ""
  },
  {
    "id": "OP03-098",
    "name": "Enies Lobby",
    "category": "STAGE",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP03-098.png?240725",
    "effect": "[Activate: Main] You may rest this Stage: If your Leader's type includes \"CP\", give up to 1 of your opponent's Characters −2 cost during this turn.",
    "type": "World Government",
    "cost": "2",
    "atribbute": ""
  },
  {
    "id": "OP04-020",
    "name": "Issho",
    "category": "LEADER",
    "color": "Green/Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP04-020.png?240725",
    "effect": "[DON!! x1] [Your Turn] Give all of your opponent's Characters −1 cost.[End of Your Turn] ➀ (You may rest the specified number of DON!! cards in your cost area.): Set up to 1 of your Characters with a cost of 5 or less as active.",
    "type": "Navy",
    "cost": "4",
    "atribbute": "Special"
  },
  {
    "id": "OP04-039",
    "name": "Rebecca",
    "category": "LEADER",
    "color": "Blue/Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP04-039.png?240725",
    "effect": "This Leader cannot attack.[Activate: Main] [Once Per Turn] ➀ (You may rest the specified number of DON!! cards in your cost area.): If you have 6 or less cards in your hand, look at 2 cards from the top of your deck; reveal up to 1 {Dressrosa} type card and add it to your hand. Then, trash the rest.",
    "type": "Dressrosa",
    "cost": "5",
    "atribbute": "Slash"
  },
  {
    "id": "OP04-077",
    "name": "Ideo",
    "category": "CHARACTER",
    "color": "Black",
    "power": "2000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP04-077.png?240725",
    "effect": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)",
    "type": "Dressrosa",
    "cost": "2",
    "atribbute": "Strike"
  },
  {
    "id": "OP04-078",
    "name": "Oimo & Kashii",
    "category": "CHARACTER",
    "color": "Black",
    "power": "8000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP04-078.png?240725",
    "effect": "-",
    "type": "Giant/World Government",
    "cost": "6",
    "atribbute": "Strike"
  },
  {
    "id": "OP04-079",
    "name": "Orlumbus",
    "category": "CHARACTER",
    "color": "Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP04-079.png?240725",
    "effect": "[Activate: Main] [Once Per Turn] Give up to 1 of your opponent's Characters −4 cost during this turn and trash 2 cards from the top of your deck. Then, K.O. 1 of your {Dressrosa} type Characters.",
    "type": "Dressrosa/Yonta Maria Fleet",
    "cost": "4",
    "atribbute": "Strike"
  },
  {
    "id": "OP04-080",
    "name": "Gyats",
    "category": "CHARACTER",
    "color": "Black",
    "power": "1000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP04-080.png?240725",
    "effect": "[On Play] Up to 1 of your {Dressrosa} type Characters can also attack active Characters during this turn.",
    "type": "Dressrosa",
    "cost": "1",
    "atribbute": "Wisdom"
  },
  {
    "id": "OP04-081",
    "name": "Cavendish",
    "category": "CHARACTER",
    "color": "Black",
    "power": "6000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP04-081.png?240725",
    "effect": "[DON!! x1] This Character can also attack active Characters.[When Attacking] You may rest your Leader: K.O. up to 1 of your opponent's Characters with a cost of 1 or less. Then, trash 2 cards from the top of your deck.",
    "type": "Dressrosa/Beautiful Pirates",
    "cost": "5",
    "atribbute": "Slash"
  },
  {
    "id": "OP04-082",
    "name": "Kyros",
    "category": "CHARACTER",
    "color": "Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP04-082.png?240725",
    "effect": "If this Character would be K.O.'d, you may rest your Leader or 1 [Corrida Coliseum] instead.[On Play] If your Leader is [Rebecca], K.O. up to 1 of your opponent's Characters with a cost of 1 or less. Then, trash 1 card from the top of your deck.",
    "type": "Dressrosa",
    "cost": "3",
    "atribbute": "Slash"
  },
  {
    "id": "OP04-083",
    "name": "Sabo",
    "category": "CHARACTER",
    "color": "Black",
    "power": "6000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP04-083.png?240725",
    "effect": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)[On Play] None of your Characters can be K.O.'d by effects until the start of your next turn. Then, draw 2 cards and trash 2 cards from your hand.",
    "type": "Dressrosa/Revolutionary Army",
    "cost": "5",
    "atribbute": "Special"
  },
  {
    "id": "OP04-084",
    "name": "Stussy",
    "category": "CHARACTER",
    "color": "Black",
    "power": "3000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP04-084.png?240725",
    "effect": "[On Play] Look at 3 cards from the top of your deck and play up to 1 Character card with a type including \"CP\" other than [Stussy] and a cost of 2 or less. Then, trash the rest.",
    "type": "CP0",
    "cost": "2",
    "atribbute": "Special"
  },
  {
    "id": "OP04-085",
    "name": "Suleiman",
    "category": "CHARACTER",
    "color": "Black",
    "power": "4000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP04-085.png?240725",
    "effect": "[On Play]/[When Attacking] If your Leader has the {Dressrosa} type, give up to 1 of your opponent's Characters −2 cost during this turn. Then, trash 1 card from the top of your deck.",
    "type": "Dressrosa",
    "cost": "3",
    "atribbute": "Slash"
  },
  {
    "id": "OP04-086",
    "name": "Chinjao",
    "category": "CHARACTER",
    "color": "Black",
    "power": "6000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP04-086.png?240725",
    "effect": "[DON!! x1] When this Character battles and K.O.'s your opponent's Character, draw 2 cards and trash 2 cards from your hand.",
    "type": "Dressrosa/Happosui Army",
    "cost": "5",
    "atribbute": "Strike"
  },
  {
    "id": "OP04-087",
    "name": "Trafalgar Law",
    "category": "CHARACTER",
    "color": "Black",
    "power": "7000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP04-087.png?240725",
    "effect": "-",
    "type": "Dressrosa/Heart Pirates",
    "cost": "5",
    "atribbute": "Slash"
  },
  {
    "id": "OP04-088",
    "name": "Hajrudin",
    "category": "CHARACTER",
    "color": "Black",
    "power": "7000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP04-088.png?240725",
    "effect": "[Activate: Main] You may rest your 1 Leader: Give up to 1 of your opponent's Characters −4 cost during this turn.",
    "type": "Giant/Dressrosa/New Giant Pirates",
    "cost": "6",
    "atribbute": "Strike"
  },
  {
    "id": "OP04-089",
    "name": "Bartolomeo",
    "category": "CHARACTER",
    "color": "Black",
    "power": "3000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP04-089.png?240725",
    "effect": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)",
    "type": "Dressrosa/Barto Club",
    "cost": "3",
    "atribbute": "Special"
  },
  {
    "id": "OP04-090",
    "name": "Monkey.D.Luffy",
    "category": "CHARACTER",
    "color": "Black",
    "power": "7000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP04-090.png?240725",
    "effect": "This Character can also attack active Characters.[Activate: Main] [Once Per Turn] You may return 7 cards from your trash to the bottom of your deck in any order: Set this Character as active. Then, this Character will not become active in your next Refresh Phase.",
    "type": "Dressrosa/Straw Hat Crew",
    "cost": "7",
    "atribbute": "Strike"
  },
  {
    "id": "OP04-091",
    "name": "Leo",
    "category": "CHARACTER",
    "color": "Black",
    "power": "2000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP04-091.png?240725",
    "effect": "[On Play] You may rest your 1 Leader: If your Leader has the {Dressrosa} type, K.O. up to 1 of your opponent's Characters with a cost of 1 or less. Then, trash 2 cards from the top of your deck.",
    "type": "The Tontattas/Dressrosa",
    "cost": "1",
    "atribbute": "Strike"
  },
  {
    "id": "OP04-092",
    "name": "Rebecca",
    "category": "CHARACTER",
    "color": "Black",
    "power": "2000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP04-092.png?240725",
    "effect": "[On Play] Look at 3 cards from the top of your deck; reveal up to 1 {Dressrosa} type card other than [Rebecca] and add it to your hand. Then, trash the rest.",
    "type": "Dressrosa",
    "cost": "1",
    "atribbute": "Slash"
  },
  {
    "id": "OP04-093",
    "name": "Gum-Gum King Kong Gun",
    "category": "EVENT",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP04-093.png?240725",
    "effect": "[Main] Up to 1 of your {Dressrosa} type Characters gains +6000 power during this turn. Then, if you have 15 or more cards in your trash, that card gains [Double Attack] during this turn.(This card deals 2 damage.)",
    "type": "Dressrosa/Straw Hat Crew",
    "cost": "3",
    "atribbute": ""
  },
  {
    "id": "OP04-094",
    "name": "Trueno Bastardo",
    "category": "EVENT",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP04-094.png?240725",
    "effect": "[Main] Choose up to 1 of your opponent's Characters with a cost of 4 or less and K.O. it. If you have 15 or more cards in your trash, choose up to 1 of your opponent's Characters with a cost of 6 or less instead of a Character with a cost of 4 or less.",
    "type": "Dressrosa",
    "cost": "4",
    "atribbute": ""
  },
  {
    "id": "OP04-095",
    "name": "Barrier!!",
    "category": "EVENT",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP04-095.png?240725",
    "effect": "[Counter] Up to 1 of your Leader or Character cards gains +2000 power during this battle. Then, if you have 15 or more cards in your trash, that card gains an additional +2000 power during this battle.",
    "type": "Dressrosa/Barto Club",
    "cost": "1",
    "atribbute": ""
  },
  {
    "id": "OP04-096",
    "name": "Corrida Coliseum",
    "category": "STAGE",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP04-096.png?240725",
    "effect": "If your Leader has the {Dressrosa} type, your {Dressrosa} type Characters can attack Characters on the turn in which they are played.",
    "type": "Dressrosa",
    "cost": "1",
    "atribbute": ""
  },
  {
    "id": "OP05-001",
    "name": "Sabo",
    "category": "LEADER",
    "color": "Red/Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP05-001.png?240725",
    "effect": "[DON!! x1] [Opponent's Turn] [Once Per Turn] If your Character with 5000 power or more would be K.O.'d, you may give that Character −1000 power during this turn instead of that Character being K.O.'d.",
    "type": "Revolutionary Army",
    "cost": "4",
    "atribbute": "Special"
  },
  {
    "id": "OP05-041",
    "name": "Sakazuki",
    "category": "LEADER",
    "color": "Blue/Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP05-041.png?240725",
    "effect": "[Activate: Main] [Once Per Turn] You may trash 1 card from your hand: Draw 1 card.[When Attacking] Give up to 1 of your opponent's Characters −1 cost during this turn.",
    "type": "Navy",
    "cost": "4",
    "atribbute": "Special"
  },
  {
    "id": "OP05-079",
    "name": "Viola",
    "category": "CHARACTER",
    "color": "Black",
    "power": "3000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP05-079.png?240725",
    "effect": "[On Play] Your opponent places 3 cards from their trash at the bottom of their deck in any order.",
    "type": "Dressrosa",
    "cost": "2",
    "atribbute": "Special"
  },
  {
    "id": "OP05-080",
    "name": "Elizabello II",
    "category": "CHARACTER",
    "color": "Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP05-080.png?240725",
    "effect": "[When Attacking] [Once Per Turn] You may return 20 cards from your trash to your deck and shuffle it: This Character gains [Double Attack] and +10000 power during this battle.(This card deals 2 damage.)",
    "type": "Kingdom of Prodence/Dressrosa",
    "cost": "4",
    "atribbute": "Strike"
  },
  {
    "id": "OP05-081",
    "name": "One-Legged Toy Soldier",
    "category": "CHARACTER",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP05-081.png?240725",
    "effect": "[Activate: Main] You may trash this Character: Give up to 1 of your opponent's Characters −3 cost during this turn.",
    "type": "Dressrosa",
    "cost": "2",
    "atribbute": "Strike"
  },
  {
    "id": "OP05-082",
    "name": "Shirahoshi",
    "category": "CHARACTER",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP05-082.png?240725",
    "effect": "[Activate: Main] You may rest this Character and place 2 cards from your trash at the bottom of your deck in any order: If your opponent has 6 or more cards in their hand, your opponent trashes 1 card from their hand.",
    "type": "Merfolk",
    "cost": "1",
    "atribbute": "Wisdom"
  },
  {
    "id": "OP05-083",
    "name": "Sterry",
    "category": "CHARACTER",
    "color": "Black",
    "power": "4000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP05-083.png?240725",
    "effect": "-",
    "type": "Goa Kingdom",
    "cost": "2",
    "atribbute": "Wisdom"
  },
  {
    "id": "OP05-084",
    "name": "Saint Charlos",
    "category": "CHARACTER",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP05-084.png?240725",
    "effect": "[Your Turn] If the only Characters on your field are {Celestial Dragons} type Characters, give all of your opponent's Characters −4 cost.",
    "type": "Celestial Dragons",
    "cost": "3",
    "atribbute": "Ranged"
  },
  {
    "id": "OP05-085",
    "name": "Nefeltari Cobra",
    "category": "CHARACTER",
    "color": "Black",
    "power": "1000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP05-085.png?240725",
    "effect": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)[On Play] Trash 1 card from the top of your deck.",
    "type": "Alabasta",
    "cost": "2",
    "atribbute": "Wisdom"
  },
  {
    "id": "OP05-086",
    "name": "Nefeltari Vivi",
    "category": "CHARACTER",
    "color": "Black",
    "power": "1000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP05-086.png?240725",
    "effect": "If you have 10 or more cards in your trash, this Character gains [Blocker].(After your opponent declares an attack, you may rest this card to make it the new target of the attack.)",
    "type": "Alabasta",
    "cost": "1",
    "atribbute": "Wisdom"
  },
  {
    "id": "OP05-087",
    "name": "Hakuba",
    "category": "CHARACTER",
    "color": "Black",
    "power": "6000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP05-087.png?240725",
    "effect": "[DON!! x1] [When Attacking] You may K.O. 1 of your Characters other than this Character: Give up to 1 of your opponent's Characters −5 cost during this turn.",
    "type": "Dressrosa/Beautiful Pirates",
    "cost": "5",
    "atribbute": "Slash"
  },
  {
    "id": "OP05-088",
    "name": "Mansherry",
    "category": "CHARACTER",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP05-088.png?240725",
    "effect": "[Activate: Main] ➀ (You may rest the specified number of DON!! cards in your cost area.) You may rest this Character and place 2 cards from your trash at the bottom of your deck in any order: Add up to 1 black Character card with a cost of 3 to 5 from your trash to your hand.",
    "type": "The Tontattas/Dressrosa",
    "cost": "1",
    "atribbute": "Special"
  },
  {
    "id": "OP05-089",
    "name": "Saint Mjosgard",
    "category": "CHARACTER",
    "color": "Black",
    "power": "1000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP05-089.png?240725",
    "effect": "[Activate: Main] ➀ (You may rest the specified number of DON!! cards in your cost area.) You may rest this Character and 1 of your Characters: Add up to 1 black Character card with a cost of 1 from your trash to your hand.",
    "type": "Celestial Dragons",
    "cost": "5",
    "atribbute": "Wisdom"
  },
  {
    "id": "OP05-090",
    "name": "Riku Doldo III",
    "category": "CHARACTER",
    "color": "Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP05-090.png?240725",
    "effect": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)[On Play]/[On K.O.] Up to 1 of your {Dressrosa} type Characters gains +2000 power during this turn.",
    "type": "Dressrosa",
    "cost": "4",
    "atribbute": "Wisdom"
  },
  {
    "id": "OP05-091",
    "name": "Rebecca",
    "category": "CHARACTER",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP05-091.png?240725",
    "effect": "[Blocker][On Play] Add up to 1 black Character card with a cost of 3 to 7 other than [Rebecca] from your trash to your hand. Then, play up to 1 black Character card with a cost of 3 or less from your hand rested.",
    "type": "Dressrosa",
    "cost": "4",
    "atribbute": "Wisdom"
  },
  {
    "id": "OP05-092",
    "name": "Saint Rosward",
    "category": "CHARACTER",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP05-092.png?240725",
    "effect": "[Your Turn] If the only Characters on your field are {Celestial Dragons} type Characters, give all of your opponent's Characters −6 cost.",
    "type": "Celestial Dragons",
    "cost": "5",
    "atribbute": "Ranged"
  },
  {
    "id": "OP05-093",
    "name": "Rob Lucci",
    "category": "CHARACTER",
    "color": "Black",
    "power": "6000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP05-093.png?240725",
    "effect": "[On Play] You may place 3 cards from your trash at the bottom of your deck in any order: K.O. up to 1 of your opponent's Characters with a cost of 2 or less and up to 1 of your opponent's Characters with a cost of 1 or less.",
    "type": "CP0",
    "cost": "4",
    "atribbute": "Strike"
  },
  {
    "id": "OP05-094",
    "name": "Haute Couture Patch★Work",
    "category": "EVENT",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP05-094.png?240725",
    "effect": "[Main] Give up to 1 of your opponent's Characters −3 cost during this turn. Then, up to 1 of your opponent's Characters with a cost of 0 will not become active in the next Refresh Phase.",
    "type": "The Tontattas/Dressrosa",
    "cost": "1",
    "atribbute": ""
  },
  {
    "id": "OP05-095",
    "name": "Dragon Claw",
    "category": "EVENT",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP05-095.png?240725",
    "effect": "[Counter] Up to 1 of your Leader or Character cards gains +4000 power during this battle. Then, if you have 15 or more cards in your trash, K.O. up to 1 of your opponent's Characters with a cost of 4 or less.",
    "type": "Dressrosa/Revolutionary Army",
    "cost": "2",
    "atribbute": ""
  },
  {
    "id": "OP05-096",
    "name": "I Bid 500 Million!!",
    "category": "EVENT",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP05-096.png?240725",
    "effect": "[Main] Choose one:• K.O. up to 1 of your opponent's Characters with a cost of 1 or less.• Return up to 1 of your opponent's Characters with a cost of 1 or less to the owner's hand.• Place up to 1 of your opponent's Characters with a cost of 1 or less at the top or bottom of their Life cards face-up.Then, if you have a {Celestial Dragons} type Character, draw 1 card.",
    "type": "Celestial Dragons",
    "cost": "3",
    "atribbute": ""
  },
  {
    "id": "OP05-097",
    "name": "Mary Geoise",
    "category": "STAGE",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP05-097.png?240725",
    "effect": "[Your Turn] The cost of playing {Celestial Dragons} type Character cards with a cost of 2 or more from your hand will be reduced by 1.",
    "type": "Mary Geoise",
    "cost": "1",
    "atribbute": ""
  },
  {
    "id": "OP06-021",
    "name": "Perona",
    "category": "LEADER",
    "color": "Green/Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP06-021.png?240725",
    "effect": "[Activate: Main] [Once Per Turn] Choose one:• Rest up to 1 of your opponent's Characters with a cost of 4 or less.• Give up to 1 of your opponent's Characters −1 cost during this turn.",
    "type": "Thriller Bark Pirates",
    "cost": "4",
    "atribbute": "Special"
  },
  {
    "id": "OP06-080",
    "name": "Gecko Moria",
    "category": "LEADER",
    "color": "Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP06-080.png?240725",
    "effect": "[DON!! x1] [When Attacking] ➁ (You may rest the specified number of DON!! cards in your cost area.) You may trash 1 card from your hand: Trash 2 cards from the top of your deck and play up to 1 {Thriller Bark Pirates} type Character card with a cost of 4 or less from your trash.",
    "type": "The Seven Warlords of the Sea/Thriller Bark Pirates",
    "cost": "5",
    "atribbute": "Special"
  },
  {
    "id": "OP06-081",
    "name": "Absalom",
    "category": "CHARACTER",
    "color": "Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP06-081.png?240725",
    "effect": "[On Play] You may return 2 cards from your trash to the bottom of your deck in any order: K.O. up to 1 Character with a cost of 2 or less.",
    "type": "Thriller Bark Pirates",
    "cost": "4",
    "atribbute": "Ranged"
  },
  {
    "id": "OP06-082",
    "name": "Inuppe",
    "category": "CHARACTER",
    "color": "Black",
    "power": "3000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP06-082.png?240725",
    "effect": "[On Play]/[On K.O.] If your Leader has the {Thriller Bark Pirates} type, draw 2 cards and trash 2 cards from your hand.",
    "type": "Thriller Bark Pirates",
    "cost": "2",
    "atribbute": "Strike"
  },
  {
    "id": "OP06-083",
    "name": "Oars",
    "category": "CHARACTER",
    "color": "Black",
    "power": "7000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP06-083.png?240725",
    "effect": "This Character cannot attack.[Activate: Main] You may K.O. 1 of your {Thriller Bark Pirates} type Characters: This Character's effect is negated during this turn.",
    "type": "Giant/Thriller Bark Pirates",
    "cost": "4",
    "atribbute": "Strike"
  },
  {
    "id": "OP06-084",
    "name": "Jigoro of the Wind",
    "category": "CHARACTER",
    "color": "Black",
    "power": "3000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP06-084.png?240725",
    "effect": "[On K.O.] Up to 1 of your Leader or Character cards gains +1000 power during this turn.",
    "type": "Thriller Bark Pirates",
    "cost": "2",
    "atribbute": "Slash"
  },
  {
    "id": "OP06-085",
    "name": "Kumacy",
    "category": "CHARACTER",
    "color": "Black",
    "power": "3000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP06-085.png?240725",
    "effect": "[DON!! x2] [Your Turn] This Character gains +1000 power for every 5 cards in your trash.",
    "type": "Thriller Bark Pirates",
    "cost": "2",
    "atribbute": "Strike"
  },
  {
    "id": "OP06-086",
    "name": "Gecko Moria",
    "category": "CHARACTER",
    "color": "Black",
    "power": "9000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP06-086.png?240725",
    "effect": "[On Play] Choose up to 1 Character card with a cost of 4 or less and up to 1 Character card with a cost of 2 or less from your trash. Play 1 card and play the other card rested.",
    "type": "The Seven Warlords of the Sea/Thriller Bark Pirates",
    "cost": "8",
    "atribbute": "Special"
  },
  {
    "id": "OP06-087",
    "name": "Cerberus",
    "category": "CHARACTER",
    "color": "Black",
    "power": "2000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP06-087.png?240725",
    "effect": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)",
    "type": "Thriller Bark Pirates",
    "cost": "2",
    "atribbute": "Strike"
  },
  {
    "id": "OP06-088",
    "name": "Sai",
    "category": "CHARACTER",
    "color": "Black",
    "power": "4000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP06-088.png?240725",
    "effect": "If your Leader has the {Dressrosa} type and is active, this Character gains +2000 power.",
    "type": "Dressrosa/Happosui Army",
    "cost": "3",
    "atribbute": "Slash"
  },
  {
    "id": "OP06-089",
    "name": "Taralan",
    "category": "CHARACTER",
    "color": "Black",
    "power": "3000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP06-089.png?240725",
    "effect": "[On Play]/[On K.O.] Trash 3 cards from the top of your deck.",
    "type": "Thriller Bark Pirates",
    "cost": "2",
    "atribbute": "Special"
  },
  {
    "id": "OP06-090",
    "name": "Dr. Hogback",
    "category": "CHARACTER",
    "color": "Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP06-090.png?240725",
    "effect": "[On Play] You may return 2 cards from your trash to the bottom of your deck in any order: Add up to 1 {Thriller Bark Pirates} type card other than [Dr. Hogback] from your trash to your hand.",
    "type": "Thriller Bark Pirates",
    "cost": "4",
    "atribbute": "Wisdom"
  },
  {
    "id": "OP06-091",
    "name": "Victoria Cindry",
    "category": "CHARACTER",
    "color": "Black",
    "power": "2000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP06-091.png?240725",
    "effect": "[On Play] If your Leader has the {Thriller Bark Pirates} type, trash 5 cards from the top of your deck.",
    "type": "Thriller Bark Pirates",
    "cost": "1",
    "atribbute": "Slash"
  },
  {
    "id": "OP06-092",
    "name": "Brook",
    "category": "CHARACTER",
    "color": "Black",
    "power": "6000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP06-092.png?240725",
    "effect": "[On Play] Choose one:• Trash up to 1 of your opponent's Characters with a cost of 4 or less.• Your opponent places 3 cards from their trash at the bottom of their deck in any order.",
    "type": "Former Rumbar Pirates",
    "cost": "6",
    "atribbute": "Slash"
  },
  {
    "id": "OP06-093",
    "name": "Perona",
    "category": "CHARACTER",
    "color": "Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP06-093.png?240725",
    "effect": "[On Play] If your opponent has 5 or more cards in their hand, choose one:• Your opponent trashes 1 card from their hand.• Give up to 1 of your opponent's Characters −3 cost during this turn.",
    "type": "Thriller Bark Pirates",
    "cost": "4",
    "atribbute": "Special"
  },
  {
    "id": "OP06-094",
    "name": "Lola",
    "category": "CHARACTER",
    "color": "Black",
    "power": "6000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP06-094.png?240725",
    "effect": "-",
    "type": "Thriller Bark Pirates",
    "cost": "4",
    "atribbute": "Slash"
  },
  {
    "id": "OP06-095",
    "name": "Shadows Asgard",
    "category": "EVENT",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP06-095.png?240725",
    "effect": "[Main]/[Counter] Your Leader gains +1000 power during this turn. Then, you may K.O. any number of your {Thriller Bark Pirates} type Characters with a cost of 2 or less. Your Leader gains an additional +1000 power during this turn for every Character K.O.'d.",
    "type": "The Seven Warlords of the Sea/Thriller Bark Pirates",
    "cost": "2",
    "atribbute": ""
  },
  {
    "id": "OP06-096",
    "name": "...Nothing...at All!!!",
    "category": "EVENT",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP06-096.png?240725",
    "effect": "[Counter] You may add 1 card from the top of your Life cards to your hand: Your Characters with a cost of 7 or less cannot be K.O.'d in battle during this turn.",
    "type": "Straw Hat Crew",
    "cost": "3",
    "atribbute": ""
  },
  {
    "id": "OP06-097",
    "name": "Negative Hollow",
    "category": "EVENT",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP06-097.png?240725",
    "effect": "[Main] Trash 1 card from your opponent's hand.",
    "type": "Thriller Bark Pirates",
    "cost": "2",
    "atribbute": ""
  },
  {
    "id": "OP06-098",
    "name": "Thriller Bark",
    "category": "STAGE",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP06-098.png?240725",
    "effect": "[Activate: Main] ➀ (You may rest the specified number of DON!! cards in your cost area.) You may rest this Stage: If your Leader has the {Thriller Bark Pirates} type, play up to 1 {Thriller Bark Pirates} type Character card with a cost of 2 or less from your trash rested.",
    "type": "Thriller Bark Pirates",
    "cost": "1",
    "atribbute": ""
  },
  {
    "id": "OP07-079",
    "name": "Rob Lucci",
    "category": "LEADER",
    "color": "Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP07-079.png?240725",
    "effect": "[When Attacking] You may trash 2 cards from the top of your deck: Give up to 1 of your opponent's Characters −1 cost during this turn.",
    "type": "CP0",
    "cost": "5",
    "atribbute": "Strike"
  },
  {
    "id": "OP07-080",
    "name": "Kaku",
    "category": "CHARACTER",
    "color": "Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP07-080.png?240725",
    "effect": "[On Play] You may place 2 cards with a type including \"CP\" from your trash at the bottom of your deck in any order: Give up to 1 of your opponent's Characters −3 cost during this turn.",
    "type": "CP0",
    "cost": "4",
    "atribbute": "Slash"
  },
  {
    "id": "OP07-081",
    "name": "Kalifa",
    "category": "CHARACTER",
    "color": "Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP07-081.png?240725",
    "effect": "[DON!! x1] [Your Turn] Give all of your opponent's Characters −1 cost.",
    "type": "CP0",
    "cost": "4",
    "atribbute": "Special"
  },
  {
    "id": "OP07-082",
    "name": "Captain John",
    "category": "CHARACTER",
    "color": "Black",
    "power": "3000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP07-082.png?240725",
    "effect": "[On Play] Trash 2 cards from the top of your deck and give up to 1 of your opponent's Characters −1 cost during this turn.",
    "type": "Thriller Bark Pirates/Former Rocks Pirates",
    "cost": "2",
    "atribbute": "Slash"
  },
  {
    "id": "OP07-083",
    "name": "Gecko Moria",
    "category": "CHARACTER",
    "color": "Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP07-083.png?240725",
    "effect": "[Activate: Main] You may place 4 {Thriller Bark Pirates} type cards from your trash at the bottom of your deck in any order: This Character gains [Banish] and +1000 power during this turn.(When this card deals damage, the target card is trashed without activating its Trigger.)",
    "type": "The Seven Warlords of the Sea/Thriller Bark Pirates",
    "cost": "4",
    "atribbute": "Special"
  },
  {
    "id": "OP07-084",
    "name": "Gismonda",
    "category": "CHARACTER",
    "color": "Black",
    "power": "2000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP07-084.png?240725",
    "effect": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)",
    "type": "CP0",
    "cost": "2",
    "atribbute": "Strike"
  },
  {
    "id": "OP07-085",
    "name": "Stussy",
    "category": "CHARACTER",
    "color": "Black",
    "power": "9000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP07-085.png?240725",
    "effect": "[On Play] You may trash 1 of your Characters: K.O. up to 1 of your opponent's Characters.",
    "type": "CP0",
    "cost": "9",
    "atribbute": "Special"
  },
  {
    "id": "OP07-086",
    "name": "Spandam",
    "category": "CHARACTER",
    "color": "Black",
    "power": "4000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP07-086.png?240725",
    "effect": "[On Play] Trash 2 cards from the top of your deck and give up to 1 of your opponent's Characters −2 cost during this turn.",
    "type": "CP0",
    "cost": "3",
    "atribbute": "Slash"
  },
  {
    "id": "OP07-087",
    "name": "Baskerville",
    "category": "CHARACTER",
    "color": "Black",
    "power": "3000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP07-087.png?240725",
    "effect": "[Your Turn] If your opponent has a Character with a cost of 0, this Character gains +3000 power.",
    "type": "World Government",
    "cost": "3",
    "atribbute": "Slash"
  },
  {
    "id": "OP07-088",
    "name": "Hattori",
    "category": "CHARACTER",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP07-088.png?240725",
    "effect": "[Your Turn] [On Play] Up to 1 of your [Rob Lucci] cards gains +2000 power during this turn.",
    "type": "Animal/CP0",
    "cost": "1",
    "atribbute": "Strike"
  },
  {
    "id": "OP07-089",
    "name": "Maha",
    "category": "CHARACTER",
    "color": "Black",
    "power": "8000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP07-089.png?240725",
    "effect": "-",
    "type": "CP0",
    "cost": "6",
    "atribbute": "Strike"
  },
  {
    "id": "OP07-090",
    "name": "Morgans",
    "category": "CHARACTER",
    "color": "Black",
    "power": "2000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP07-090.png?240725",
    "effect": "[On Play] Your opponent trashes 1 card from their hand and reveals their hand. Then, your opponent draws 1 card.",
    "type": "Journalist",
    "cost": "2",
    "atribbute": "Wisdom"
  },
  {
    "id": "OP07-091",
    "name": "Monkey.D.Luffy",
    "category": "CHARACTER",
    "color": "Black",
    "power": "6000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP07-091.png?240725",
    "effect": "[When Attacking] Trash up to 1 of your opponent's Characters with a cost of 2 or less. Then, place any number of Character cards with a cost of 4 or more from your trash at the bottom of your deck in any order. This Character gains +1000 power during this turn for every 3 cards placed at the bottom of your deck.",
    "type": "Straw Hat Crew",
    "cost": "5",
    "atribbute": "Special"
  },
  {
    "id": "OP07-092",
    "name": "Joseph",
    "category": "CHARACTER",
    "color": "Black",
    "power": "2000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP07-092.png?240725",
    "effect": "[On Play] You may place 2 cards with a type including \"CP\" from your trash at the bottom of your deck in any order: K.O. up to 1 of your opponent's Characters with a cost of 1 or less.",
    "type": "CP0",
    "cost": "1",
    "atribbute": "Strike"
  },
  {
    "id": "OP07-093",
    "name": "Rob Lucci",
    "category": "CHARACTER",
    "color": "Black",
    "power": "6000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP07-093.png?240725",
    "effect": "[On Play] You may place 3 cards from your trash at the bottom of your deck in any order: Your opponent trashes 1 card from their hand. Then, you may place up to 1 card from your opponent's trash at the bottom of their deck.",
    "type": "CP0",
    "cost": "5",
    "atribbute": "Strike"
  },
  {
    "id": "OP07-094",
    "name": "Shave",
    "category": "EVENT",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP07-094.png?240725",
    "effect": "[Counter] Up to 1 of your Leader or Character cards gains +2000 power during this battle. Then, if you have 10 or more cards in your trash, return up to 1 of your Characters with a type including \"CP\" to the owner's hand.",
    "type": "CP9",
    "cost": "1",
    "atribbute": ""
  },
  {
    "id": "OP07-095",
    "name": "Iron Body",
    "category": "EVENT",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP07-095.png?240725",
    "effect": "[Counter] Up to 1 of your Leader or Character cards gains +4000 power during this battle. Then, if you have 10 or more cards in your trash, that card gains an additional +2000 power during this battle.",
    "type": "CP9",
    "cost": "2",
    "atribbute": ""
  },
  {
    "id": "OP07-096",
    "name": "Tempest Kick",
    "category": "EVENT",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP07-096.png?240725",
    "effect": "[Main] Draw 1 card. Then, if you have 10 or more cards in your trash, give up to 1 of your opponent's Characters −3 cost during this turn.",
    "type": "CP9",
    "cost": "1",
    "atribbute": ""
  },
  {
    "id": "OP07-118",
    "name": "Sabo",
    "category": "CHARACTER",
    "color": "Black",
    "power": "9000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP07-118.png?240725",
    "effect": "[On Play] You may trash 1 card from your hand: K.O. up to 1 of your opponent's Characters with a cost of 5 or less and up to 1 of your opponent's Characters with a cost of 3 or less.",
    "type": "Revolutionary Army",
    "cost": "8",
    "atribbute": "Special"
  },
  {
    "id": "P-025",
    "name": "Smoker",
    "category": "CHARACTER",
    "color": "Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/P-025.png?240725",
    "effect": "[DON!! x1] This Character cannot be K.O.'d in battle by Characters without the <Special> attribute.",
    "type": "Navy",
    "cost": "3",
    "atribbute": "Special"
  },
  {
    "id": "P-026",
    "name": "Morgan",
    "category": "CHARACTER",
    "color": "Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/P-026.png?240725",
    "effect": "[When Attacking] Give up to 1 of your opponent's Characters −3 cost during this turn.",
    "type": "Navy",
    "cost": "4",
    "atribbute": "Slash"
  },
  {
    "id": "P-032",
    "name": "Sengoku",
    "category": "CHARACTER",
    "color": "Black",
    "power": "6000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/P-032.png?240725",
    "effect": "[DON!! x1] [Your Turn] Give all of your opponent's Characters −2 cost.",
    "type": "Navy",
    "cost": "5",
    "atribbute": "Wisdom"
  },
  {
    "id": "P-035",
    "name": "Monkey.D.Luffy",
    "category": "CHARACTER",
    "color": "Black",
    "power": "6000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/P-035.png?240725",
    "effect": "[DON!! x1] [When Attacking] You may trash 1 card from your hand: K.O. up to 1 of your opponent's Characters with a cost of 0.",
    "type": "Straw Hat Crew",
    "cost": "6",
    "atribbute": "Strike"
  },
  {
    "id": "P-076",
    "name": "Sakazuki",
    "category": "LEADER",
    "color": "Blue/Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/P-076.png?240725",
    "effect": "[Activate: Main] [Once Per Turn] You may trash 1 {Navy} type card from your hand: Give up to 1 of your opponent's Characters －1 cost during this turn.",
    "type": "Navy",
    "cost": "4",
    "atribbute": "Special"
  },
  {
    "id": "ST06-001",
    "name": "Sakazuki",
    "category": "LEADER",
    "color": "Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST06-001.png?240725",
    "effect": "[Activate: Main] [Once Per Turn] ③ (You may rest the specified number of DON!! cards in your cost area.) You may trash 1 card from your hand: K.O. up to 1 of your opponent's Characters with a cost of 0.",
    "type": "Navy",
    "cost": "5",
    "atribbute": "Special"
  },
  {
    "id": "ST06-002",
    "name": "Koby",
    "category": "CHARACTER",
    "color": "Black",
    "power": "2000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST06-002.png?240725",
    "effect": "[On Play] You may trash 1 card from your hand: K.O. up to 1 of your opponent's Characters with a cost of 0.",
    "type": "Navy",
    "cost": "1",
    "atribbute": "Strike"
  },
  {
    "id": "ST06-003",
    "name": "Jango",
    "category": "CHARACTER",
    "color": "Black",
    "power": "3000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST06-003.png?240725",
    "effect": "-",
    "type": "Navy",
    "cost": "1",
    "atribbute": "Slash"
  },
  {
    "id": "ST06-004",
    "name": "Smoker",
    "category": "CHARACTER",
    "color": "Black",
    "power": "7000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST06-004.png?240725",
    "effect": "This Character cannot be K.O.'d by effects.[DON!! x1] If there is a Character with a cost of 0, this Character gains [Double Attack].(This card deals 2 damage.)",
    "type": "Navy",
    "cost": "5",
    "atribbute": "Special"
  },
  {
    "id": "ST06-005",
    "name": "Sengoku",
    "category": "CHARACTER",
    "color": "Black",
    "power": "6000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST06-005.png?240725",
    "effect": "[When Attacking] Give up to 1 of your opponent's Characters −4 cost during this turn.",
    "type": "Navy",
    "cost": "5",
    "atribbute": "Wisdom"
  },
  {
    "id": "ST06-006",
    "name": "Tashigi",
    "category": "CHARACTER",
    "color": "Black",
    "power": "4000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST06-006.png?240725",
    "effect": "[Activate: Main] You may rest this Character: Give up to 1 of your opponent's Characters −2 cost during this turn.",
    "type": "Navy",
    "cost": "3",
    "atribbute": "Slash"
  },
  {
    "id": "ST06-007",
    "name": "Tsuru",
    "category": "CHARACTER",
    "color": "Black",
    "power": "2000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST06-007.png?240725",
    "effect": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)",
    "type": "Navy",
    "cost": "2",
    "atribbute": "Wisdom"
  },
  {
    "id": "ST06-008",
    "name": "Hina",
    "category": "CHARACTER",
    "color": "Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST06-008.png?240725",
    "effect": "[On Play] Give up to 1 of your opponent's Characters −4 cost during this turn.",
    "type": "Navy",
    "cost": "3",
    "atribbute": "Special"
  },
  {
    "id": "ST06-009",
    "name": "Fullbody",
    "category": "CHARACTER",
    "color": "Black",
    "power": "4000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST06-009.png?240725",
    "effect": "-",
    "type": "Navy",
    "cost": "2",
    "atribbute": "Strike"
  },
  {
    "id": "ST06-010",
    "name": "Helmeppo",
    "category": "CHARACTER",
    "color": "Black",
    "power": "3000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST06-010.png?240725",
    "effect": "[On Play] Give up to 1 of your opponent's Characters −3 cost during this turn.",
    "type": "Navy",
    "cost": "2",
    "atribbute": "Slash"
  },
  {
    "id": "ST06-011",
    "name": "Momonga",
    "category": "CHARACTER",
    "color": "Black",
    "power": "6000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST06-011.png?240725",
    "effect": "-",
    "type": "Navy",
    "cost": "4",
    "atribbute": "Slash"
  },
  {
    "id": "ST06-012",
    "name": "Monkey.D.Garp",
    "category": "CHARACTER",
    "color": "Black",
    "power": "6000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST06-012.png?240725",
    "effect": "[Activate: Main] You may trash 1 card from your hand and rest this Character: K.O. up to 1 of your opponent's Characters with a cost of 4 or less.",
    "type": "Navy",
    "cost": "5",
    "atribbute": "Strike"
  },
  {
    "id": "ST06-013",
    "name": "T-Bone",
    "category": "CHARACTER",
    "color": "Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST06-013.png?240725",
    "effect": "-",
    "type": "Navy",
    "cost": "3",
    "atribbute": "Slash"
  },
  {
    "id": "ST06-014",
    "name": "Shockwave",
    "category": "EVENT",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST06-014.png?240725",
    "effect": "[Counter] Up to 1 of your Leader or Character cards gains +4000 power during this battle. Then, K.O. up to 1 of your opponent's active Characters with a cost of 3 or less.",
    "type": "Navy",
    "cost": "2",
    "atribbute": ""
  },
  {
    "id": "ST06-015",
    "name": "Great Eruption",
    "category": "EVENT",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST06-015.png?240725",
    "effect": "[Main] Draw 1 card. Then, give up to 1 of your opponent's Characters −2 cost during this turn.",
    "type": "Navy",
    "cost": "1",
    "atribbute": ""
  },
  {
    "id": "ST06-016",
    "name": "White Out",
    "category": "EVENT",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST06-016.png?240725",
    "effect": "[Counter] Up to 1 of your Leader or Character cards gains +2000 power during this battle.",
    "type": "Navy",
    "cost": "1",
    "atribbute": ""
  },
  {
    "id": "ST06-017",
    "name": "Navy HQ",
    "category": "STAGE",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST06-017.png?240725",
    "effect": "[On Play] Give up to 1 of your opponent's Characters −1 cost during this turn.[Activate: Main] You may rest this Stage: If your Leader has the {Navy} type, give up to 1 of your opponent's Characters −1 cost during this turn.",
    "type": "Navy",
    "cost": "1",
    "atribbute": ""
  },
  {
    "id": "ST08-001",
    "name": "Monkey.D.Luffy",
    "category": "LEADER",
    "color": "Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST08-001.png?240725",
    "effect": "[Your Turn] When a Character is K.O.'d, give up to 1 rested DON!! card to this Leader.",
    "type": "Straw Hat Crew",
    "cost": "5",
    "atribbute": "Strike"
  },
  {
    "id": "ST08-002",
    "name": "Uta",
    "category": "CHARACTER",
    "color": "Black",
    "power": "3000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST08-002.png?240725",
    "effect": "This Character cannot be K.O.'d in battle by Leaders.[Activate: Main] You may rest this Character: Give up to 1 of your opponent's Characters −2 cost during this turn.",
    "type": "FILM",
    "cost": "2",
    "atribbute": "Special"
  },
  {
    "id": "ST08-003",
    "name": "Gaimon",
    "category": "CHARACTER",
    "color": "Black",
    "power": "4000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST08-003.png?240725",
    "effect": "-",
    "type": "East Blue",
    "cost": "2",
    "atribbute": "Wisdom"
  },
  {
    "id": "ST08-004",
    "name": "Koby",
    "category": "CHARACTER",
    "color": "Black",
    "power": "1000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST08-004.png?240725",
    "effect": "[Activate: Main] You may rest this Character: K.O. up to 1 of your opponent's Characters with a cost of 2 or less.",
    "type": "Navy",
    "cost": "4",
    "atribbute": "Strike"
  },
  {
    "id": "ST08-005",
    "name": "Shanks",
    "category": "CHARACTER",
    "color": "Black",
    "power": "10000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST08-005.png?240725",
    "effect": "[On Play] You may trash 1 card from your hand: K.O. all Characters with a cost of 1 or less.",
    "type": "Red-Haired Pirates",
    "cost": "9",
    "atribbute": "Slash"
  },
  {
    "id": "ST08-006",
    "name": "Shirahoshi",
    "category": "CHARACTER",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST08-006.png?240725",
    "effect": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)[On Play] Give up to 1 of your opponent's Characters −4 cost during this turn.",
    "type": "Merfolk",
    "cost": "4",
    "atribbute": "Wisdom"
  },
  {
    "id": "ST08-007",
    "name": "Nefeltari Vivi",
    "category": "CHARACTER",
    "color": "Black",
    "power": "1000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST08-007.png?240725",
    "effect": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)",
    "type": "Alabasta",
    "cost": "3",
    "atribbute": "Slash"
  },
  {
    "id": "ST08-008",
    "name": "Higuma",
    "category": "CHARACTER",
    "color": "Black",
    "power": "2000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST08-008.png?240725",
    "effect": "[On Play] Give up to 1 of your opponent's Characters −2 cost during this turn.",
    "type": "Mountain Bandits",
    "cost": "1",
    "atribbute": "Slash"
  },
  {
    "id": "ST08-009",
    "name": "Makino",
    "category": "CHARACTER",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST08-009.png?240725",
    "effect": "[On Play] If there is a Character with a cost of 0, draw 1 card.",
    "type": "Windmill Village",
    "cost": "2",
    "atribbute": "Wisdom"
  },
  {
    "id": "ST08-010",
    "name": "Monkey.D.Garp",
    "category": "CHARACTER",
    "color": "Black",
    "power": "7000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST08-010.png?240725",
    "effect": "-",
    "type": "Navy",
    "cost": "5",
    "atribbute": "Strike"
  },
  {
    "id": "ST08-011",
    "name": "Monkey.D.Luffy",
    "category": "CHARACTER",
    "color": "Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST08-011.png?240725",
    "effect": "-",
    "type": "Straw Hat Crew",
    "cost": "3",
    "atribbute": "Strike"
  },
  {
    "id": "ST08-012",
    "name": "Laboon",
    "category": "CHARACTER",
    "color": "Black",
    "power": "6000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST08-012.png?240725",
    "effect": "-",
    "type": "Animal",
    "cost": "4",
    "atribbute": "Strike"
  },
  {
    "id": "ST08-013",
    "name": "Mr.2.Bon.Kurei(Bentham)",
    "category": "CHARACTER",
    "color": "Black",
    "power": "6000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST08-013.png?240725",
    "effect": "[DON!! x1] At the end of a battle in which this Character battles your opponent's Character, you may K.O. the opponent’s Character you battled with. If you do, K.O. this Character.",
    "type": "Former Baroque Works",
    "cost": "5",
    "atribbute": "Strike"
  },
  {
    "id": "ST08-014",
    "name": "Gum-Gum Bell",
    "category": "EVENT",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST08-014.png?240725",
    "effect": "[Main] You may add 1 card from the top of your Life cards to your hand: Give up to 1 of your opponent's Characters −7 cost during this turn.",
    "type": "Straw Hat Crew",
    "cost": "2",
    "atribbute": ""
  },
  {
    "id": "ST08-015",
    "name": "Gum-Gum Pistol",
    "category": "EVENT",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST08-015.png?240725",
    "effect": "[Main] K.O. up to 1 of your opponent's Characters with a cost of 2 or less.",
    "type": "Straw Hat Crew",
    "cost": "3",
    "atribbute": ""
  },
  {
    "id": "ST13-003",
    "name": "Monkey.D.Luffy",
    "category": "LEADER",
    "color": "Black/Yellow",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST13-003.png?240725",
    "effect": "Your face-up Life cards are placed at the bottom of your deck instead of being added to your hand, according to the rules.[DON!! x2] [Activate: Main] [Once Per Turn] You may trash 1 card from your hand: If you have 0 Life cards, add up to 2 Character cards with a cost of 5 from your hand or trash to the top of your Life cards face-up.",
    "type": "Supernovas/Straw Hat Crew",
    "cost": "4",
    "atribbute": "Strike"
  },
  {
    "id": "ST14-001",
    "name": "Monkey.D.Luffy",
    "category": "LEADER",
    "color": "Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST14-001.png?240725",
    "effect": "[DON!! x1] All of your Characters gain +1 cost. If you have a Character with a cost of 8 or more, this Leader gains +1000 power.",
    "type": "Straw Hat Crew",
    "cost": "5",
    "atribbute": "Strike"
  },
  {
    "id": "ST14-002",
    "name": "Usopp",
    "category": "CHARACTER",
    "color": "Black",
    "power": "4000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST14-002.png?240725",
    "effect": "[DON!! x1] [When Attacking] If you have a Character with a cost of 8 or more, K.O. up to 1 of your opponent's Characters with a cost of 4 or less.",
    "type": "Straw Hat Crew",
    "cost": "3",
    "atribbute": "Ranged"
  },
  {
    "id": "ST14-003",
    "name": "Sanji",
    "category": "CHARACTER",
    "color": "Black",
    "power": "6000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST14-003.png?240725",
    "effect": "[On Play] If you have a Character with a cost of 6 or more, K.O. up to 1 of your opponent's Characters with a cost of 5 or less.",
    "type": "Straw Hat Crew",
    "cost": "5",
    "atribbute": "Strike"
  },
  {
    "id": "ST14-004",
    "name": "Jinbe",
    "category": "CHARACTER",
    "color": "Black",
    "power": "4000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST14-004.png?240725",
    "effect": "[Activate: Main] [Once Per Turn] Up to 1 of your black {Straw Hat Crew} type Characters gains +2 cost until the end of your opponent's next turn.",
    "type": "Fish-Man/The Sun Pirates",
    "cost": "3",
    "atribbute": "Strike"
  },
  {
    "id": "ST14-005",
    "name": "Tony Tony.Chopper",
    "category": "CHARACTER",
    "color": "Black",
    "power": "6000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST14-005.png?240725",
    "effect": "-",
    "type": "Animal/Straw Hat Crew",
    "cost": "4",
    "atribbute": "Wisdom"
  },
  {
    "id": "ST14-006",
    "name": "Nami",
    "category": "CHARACTER",
    "color": "Black",
    "power": "2000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST14-006.png?240725",
    "effect": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)[On Play] If you have 6 or less cards in your hand and a Character with a cost of 8 or more, draw 1 card.",
    "type": "Straw Hat Crew",
    "cost": "3",
    "atribbute": "Special"
  },
  {
    "id": "ST14-007",
    "name": "Nico Robin",
    "category": "CHARACTER",
    "color": "Black",
    "power": "7000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST14-007.png?240725",
    "effect": "[On Play]/[When Attacking] If you have a Character with a cost of 8 or more, give up to 1 of your opponent's Characters −5 cost during this turn.",
    "type": "Straw Hat Crew",
    "cost": "6",
    "atribbute": "Strike"
  },
  {
    "id": "ST14-008",
    "name": "Haredas",
    "category": "CHARACTER",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST14-008.png?240725",
    "effect": "[Activate: Main] You may rest this Character: Up to 1 of your black {Straw Hat Crew} type Characters gains +2 cost until the end of your opponent's next turn. Then, if you have a Character with a cost of 8 or more, draw 1 card and trash 1 card from your hand.",
    "type": "Sky Island",
    "cost": "1",
    "atribbute": "Wisdom"
  },
  {
    "id": "ST14-009",
    "name": "Franky",
    "category": "CHARACTER",
    "color": "Black",
    "power": "6000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST14-009.png?240725",
    "effect": "[DON!! x1] [Opponent's Turn] If you have a Character with a cost of 6 or more, this Character cannot be K.O.'d by your opponent's effects and gains +2000 power.",
    "type": "Straw Hat Crew",
    "cost": "5",
    "atribbute": "Special"
  },
  {
    "id": "ST14-010",
    "name": "Brook",
    "category": "CHARACTER",
    "color": "Black",
    "power": "7000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST14-010.png?240725",
    "effect": "-",
    "type": "Straw Hat Crew",
    "cost": "5",
    "atribbute": "Slash"
  },
  {
    "id": "ST14-011",
    "name": "Heracles",
    "category": "CHARACTER",
    "color": "Black",
    "power": "2000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST14-011.png?240725",
    "effect": "[Activate: Main] You may rest this Character: Up to 1 of your black {Straw Hat Crew} type Characters gains +2 cost until the end of your opponent's next turn.",
    "type": "Bowin Island",
    "cost": "1",
    "atribbute": "Wisdom"
  },
  {
    "id": "ST14-012",
    "name": "Monkey.D.Luffy",
    "category": "CHARACTER",
    "color": "Black",
    "power": "10000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST14-012.png?240725",
    "effect": "If you have a Character with a cost of 10 or more, this Character gains [Rush].(This card can attack on the turn in which it is played.)",
    "type": "Straw Hat Crew",
    "cost": "8",
    "atribbute": "Strike"
  },
  {
    "id": "ST14-013",
    "name": "Roronoa Zoro",
    "category": "CHARACTER",
    "color": "Black",
    "power": "8000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST14-013.png?240725",
    "effect": "-",
    "type": "Straw Hat Crew",
    "cost": "6",
    "atribbute": "Slash"
  },
  {
    "id": "ST14-014",
    "name": "Gum-Gum Giant Rifle",
    "category": "EVENT",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST14-014.png?240725",
    "effect": "[Counter] If you have a Character with a cost of 8 or more, up to 1 of your Leader or Character cards gains +3000 power during this battle.",
    "type": "Straw Hat Crew",
    "cost": "1",
    "atribbute": ""
  },
  {
    "id": "ST14-015",
    "name": "Gum-Gum Diable Three-Swords Style Mouten Jet Six Hundred Pound Phoenix Cannon",
    "category": "EVENT",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST14-015.png?240725",
    "effect": "[Main] Up to 1 of your Leader or Character cards gains +3000 power during this turn. Then, if you have a Character with a cost of 8 or more, K.O. up to 1 of your opponent's Characters with a cost of 2 or less.",
    "type": "Straw Hat Crew",
    "cost": "2",
    "atribbute": ""
  },
  {
    "id": "ST14-016",
    "name": "I Have My Crew!!",
    "category": "EVENT",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST14-016.png?240725",
    "effect": "[Main] Draw 1 card. Then, up to 1 of your Characters gains +3 cost until the end of your opponent's next turn.",
    "type": "Straw Hat Crew",
    "cost": "1",
    "atribbute": ""
  },
  {
    "id": "ST14-017",
    "name": "Thousand Sunny",
    "category": "STAGE",
    "color": "Black",
    "power": "-",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST14-017.png?240725",
    "effect": "All of your black {Straw Hat Crew} type Characters gain +1 cost.[On Play] If your Leader has the {Straw Hat Crew} type, draw 1 card.",
    "type": "Straw Hat Crew",
    "cost": "1",
    "atribbute": ""
  },
]