export const Multicolor = [
  {
    "id": "EB01-001",
    "name": "Kouzuki Oden",
    "category": "LEADER",
    "color": "Red/Green",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/EB01-001.png?240725",
    "effect": "All of your {Land of Wano} type Character cards without a Counter have a +1000 Counter, according to the rules.[DON!! x1] [When Attacking] If you have a {Land of Wano} type Character with a cost of 5 or more, this Leader gains +1000 power until the start of your next turn.",
    "type": "Land of Wano/Kouzuki Clan",
    "cost": "4",
    "atribbute": "Slash"
  },
  {
    "id": "EB01-021",
    "name": "Hannyabal",
    "category": "LEADER",
    "color": "Blue/Purple",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/EB01-021.png?240725",
    "effect": "[End of Your Turn] You may return 1 of your {Impel Down} type Characters with a cost of 2 or more to the owner's hand: Add up to 1 DON!! card from your DON!! deck and set it as active.",
    "type": "Impel Down",
    "cost": "4",
    "atribbute": "Slash"
  },
  {
    "id": "EB01-040",
    "name": "Kyros",
    "category": "LEADER",
    "color": "Black/Yellow",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/EB01-040.png?240725",
    "effect": "[Activate: Main] [Once Per Turn] You may turn 1 card from the top of your Life cards face-up: K.O. up to 1 of your opponent's Characters with a cost of 0.",
    "type": "Dressrosa",
    "cost": "4",
    "atribbute": "Slash"
  },
  {
    "id": "OP01-002",
    "name": "Trafalgar Law",
    "category": "LEADER",
    "color": "Red/Green",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP01-002.png?240725",
    "effect": "[Activate: Main] [Once Per Turn] ➁ (You may rest the specified number of DON!! cards in your cost area.): If you have 5 Characters, return 1 of your Characters to the owner's hand. Then, play up to 1 Character with a cost of 5 or less from your hand that is a different color than the returned Character.",
    "type": "Supernovas/Heart Pirates",
    "cost": "4",
    "atribbute": "Slash"
  },
  {
    "id": "OP01-003",
    "name": "Monkey.D.Luffy",
    "category": "LEADER",
    "color": "Red/Green",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP01-003.png?240725",
    "effect": "[Activate: Main] [Once Per Turn] ➃ (You may rest the specified number of DON!! cards in your cost area.): Set up to 1 of your {Supernovas} or {Straw Hat Crew} type Character cards with a cost of 5 or less as active. It gains +1000 power during this turn.",
    "type": "Supernovas/Straw Hat Crew",
    "cost": "4",
    "atribbute": "Strike"
  },
  {
    "id": "OP01-061",
    "name": "Kaido",
    "category": "LEADER",
    "color": "Blue/Purple",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP01-061.png?240725",
    "effect": "[DON!! x1] [Your Turn] [Once Per Turn] When your opponent's Character is K.O.'d, add up to 1 DON!! card from your DON!! deck and set it as active.",
    "type": "The Four Emperors/Animal Kingdom Pirates",
    "cost": "4",
    "atribbute": "Strike"
  },
  {
    "id": "OP01-062",
    "name": "Crocodile",
    "category": "LEADER",
    "color": "Blue/Purple",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP01-062.png?240725",
    "effect": "[DON!! x1] When you activate an Event, you may draw 1 card if you have 4 or less cards in your hand and haven't drawn a card using this Leader's effect during this turn.",
    "type": "The Seven Warlords of the Sea/Baroque Works",
    "cost": "4",
    "atribbute": "Special"
  },
  {
    "id": "OP02-002",
    "name": "Monkey.D.Garp",
    "category": "LEADER",
    "color": "Red/Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-002.png?240725",
    "effect": "[Your Turn] When this Leader or any of your Characters is given a DON!! card, give up to 1 of your opponent's Characters with a cost of 7 or less −1 cost during this turn.",
    "type": "Navy",
    "cost": "4",
    "atribbute": "Strike"
  },
  {
    "id": "OP02-026",
    "name": "Sanji",
    "category": "LEADER",
    "color": "Green/Blue",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-026.png?240725",
    "effect": "[Once Per Turn] When you play a Character with no base effect from your hand, if you have 3 or less Characters, set up to 2 of your DON!! cards as active.",
    "type": "Straw Hat Crew",
    "cost": "4",
    "atribbute": "Strike"
  },
  {
    "id": "OP02-072",
    "name": "Zephyr",
    "category": "LEADER",
    "color": "Purple/Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP02-072.png?240725",
    "effect": "[When Attacking] DON!! −4 (You may return the specified number of DON!! cards from your field to your DON!! deck.): K.O. up to 1 of your opponent's Characters with a cost of 3 or less. Then, this Leader gains +1000 power during this turn.",
    "type": "FILM/Neo Navy",
    "cost": "4",
    "atribbute": "Strike"
  },
  {
    "id": "OP03-022",
    "name": "Arlong",
    "category": "LEADER",
    "color": "Green/Yellow",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP03-022.png?240725",
    "effect": "[DON!! x2] [When Attacking] ① (You may rest the specified number of DON!! cards in your cost area.): Play up to 1 Character card with a cost of 4 or less and a [Trigger] from your hand.",
    "type": "Fish-Man/East Blue/Arlong Pirates",
    "cost": "4",
    "atribbute": "Slash"
  },
  {
    "id": "OP03-077",
    "name": "Charlotte Linlin",
    "category": "LEADER",
    "color": "Black/Yellow",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP03-077.png?240725",
    "effect": "[DON!! x2] [When Attacking] ② (You may rest the specified number of DON!! cards in your cost area.) You may trash 1 card from your hand: If you have 1 or less Life cards, add up to 1 card from the top of your deck to the top of your Life cards.",
    "type": "The Four Emperors/Big Mom Pirates",
    "cost": "4",
    "atribbute": "Special"
  },
  {
    "id": "OP04-001",
    "name": "Nefeltari Vivi",
    "category": "LEADER",
    "color": "Red/Blue",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP04-001.png?240725",
    "effect": "This Leader cannot attack.[Activate: Main] [Once Per Turn] ➁ (You may rest the specified number of DON!! cards in your cost area.): Draw 1 card and up to 1 of your Characters gains [Rush] during this turn.(This card can attack on the turn in which it is played.)",
    "type": "Alabasta",
    "cost": "5",
    "atribbute": "Slash"
  },
  {
    "id": "OP04-019",
    "name": "Donquixote Doflamingo",
    "category": "LEADER",
    "color": "Green/Purple",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP04-019.png?240725",
    "effect": "[End of Your Turn] Set up to 2 of your DON!! cards as active.",
    "type": "The Seven Warlords of the Sea/Donquixote Pirates",
    "cost": "4",
    "atribbute": "Special"
  },
  {
    "id": "OP04-020",
    "name": "Issho",
    "category": "LEADER",
    "color": "Green/Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP04-020.png?240725",
    "effect": "[DON!! x1] [Your Turn] Give all of your opponent's Characters −1 cost.[End of Your Turn] ➀ (You may rest the specified number of DON!! cards in your cost area.): Set up to 1 of your Characters with a cost of 5 or less as active.",
    "type": "Navy",
    "cost": "4",
    "atribbute": "Special"
  },
  {
    "id": "OP04-039",
    "name": "Rebecca",
    "category": "LEADER",
    "color": "Blue/Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP04-039.png?240725",
    "effect": "This Leader cannot attack.[Activate: Main] [Once Per Turn] ➀ (You may rest the specified number of DON!! cards in your cost area.): If you have 6 or less cards in your hand, look at 2 cards from the top of your deck; reveal up to 1 {Dressrosa} type card and add it to your hand. Then, trash the rest.",
    "type": "Dressrosa",
    "cost": "5",
    "atribbute": "Slash"
  },
  {
    "id": "OP04-040",
    "name": "Queen",
    "category": "LEADER",
    "color": "Blue/Yellow",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP04-040.png?240725",
    "effect": "[DON!! x1] [When Attacking] If you have a total of 4 or less cards in your Life area and hand, draw 1 card. If you have a Character with a cost of 8 or more, you may add up to 1 card from the top of your deck to the top of your Life cards instead of drawing 1 card.",
    "type": "Animal Kingdom Pirates",
    "cost": "4",
    "atribbute": "Ranged"
  },
  {
    "id": "OP04-058",
    "name": "Crocodile",
    "category": "LEADER",
    "color": "Purple/Yellow",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP04-058.png?240725",
    "effect": "[Opponent's Turn] [Once Per Turn] When a DON!! card on your field is returned to your DON!! deck by your effect, add up to 1 DON!! card from your DON!! deck and set it as active.",
    "type": "The Seven Warlords of the Sea/Baroque Works",
    "cost": "4",
    "atribbute": "Special"
  },
  {
    "id": "OP05-001",
    "name": "Sabo",
    "category": "LEADER",
    "color": "Red/Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP05-001.png?240725",
    "effect": "[DON!! x1] [Opponent's Turn] [Once Per Turn] If your Character with 5000 power or more would be K.O.'d, you may give that Character −1000 power during this turn instead of that Character being K.O.'d.",
    "type": "Revolutionary Army",
    "cost": "4",
    "atribbute": "Special"
  },
  {
    "id": "OP05-002",
    "name": "Belo Betty",
    "category": "LEADER",
    "color": "Red/Yellow",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP05-002.png?240725",
    "effect": "[Activate: Main] [Once Per Turn] You may trash 1 {Revolutionary Army} type card from your hand: Up to 3 of your {Revolutionary Army} type Characters or Characters with a [Trigger] gain +3000 power during this turn.",
    "type": "Revolutionary Army",
    "cost": "4",
    "atribbute": "Special"
  },
  {
    "id": "OP05-022",
    "name": "Donquixote Rosinante",
    "category": "LEADER",
    "color": "Green/Blue",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP05-022.png?240725",
    "effect": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)[End of Your Turn] If you have 6 or less cards in your hand, set this Leader as active.",
    "type": "Navy/Donquixote Pirates",
    "cost": "4",
    "atribbute": "Special"
  },
  {
    "id": "OP05-041",
    "name": "Sakazuki",
    "category": "LEADER",
    "color": "Blue/Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP05-041.png?240725",
    "effect": "[Activate: Main] [Once Per Turn] You may trash 1 card from your hand: Draw 1 card.[When Attacking] Give up to 1 of your opponent's Characters −1 cost during this turn.",
    "type": "Navy",
    "cost": "4",
    "atribbute": "Special"
  },
  {
    "id": "OP06-001",
    "name": "Uta",
    "category": "LEADER",
    "color": "Red/Purple",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP06-001.png?240725",
    "effect": "[When Attacking] You may trash 1 {FILM} type card from your hand: Give up to 1 of your opponent's Characters −2000 power during this turn. Then, add up to 1 DON!! card from your DON!! deck and rest it.",
    "type": "FILM",
    "cost": "4",
    "atribbute": "Special"
  },
  {
    "id": "OP06-021",
    "name": "Perona",
    "category": "LEADER",
    "color": "Green/Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP06-021.png?240725",
    "effect": "[Activate: Main] [Once Per Turn] Choose one:• Rest up to 1 of your opponent's Characters with a cost of 4 or less.• Give up to 1 of your opponent's Characters −1 cost during this turn.",
    "type": "Thriller Bark Pirates",
    "cost": "4",
    "atribbute": "Special"
  },
  {
    "id": "OP06-022",
    "name": "Yamato",
    "category": "LEADER",
    "color": "Green/Yellow",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP06-022.png?240725",
    "effect": "[Double Attack] (This card deals 2 damage.)[Activate: Main] [Once Per Turn] If your opponent has 3 or less Life cards, give up to 2 rested DON!! cards to 1 of your Characters.",
    "type": "Land of Wano",
    "cost": "4",
    "atribbute": "Strike"
  },
  {
    "id": "OP06-042",
    "name": "Vinsmoke Reiju",
    "category": "LEADER",
    "color": "Blue/Purple",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/OP06-042.png?240725",
    "effect": "[Your Turn] [Once Per Turn] When a DON!! card on your field is returned to your DON!! deck, draw 1 card.",
    "type": "The Vinsmoke Family/GERMA 66",
    "cost": "4",
    "atribbute": "Special"
  },
  {
    "id": "P-076",
    "name": "Sakazuki",
    "category": "LEADER",
    "color": "Blue/Black",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/P-076.png?240725",
    "effect": "[Activate: Main] [Once Per Turn] You may trash 1 {Navy} type card from your hand: Give up to 1 of your opponent's Characters －1 cost during this turn.",
    "type": "Navy",
    "cost": "4",
    "atribbute": "Special"
  },
  {
    "id": "ST10-001",
    "name": "Trafalgar Law",
    "category": "LEADER",
    "color": "Red/Purple",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST10-001.png?240725",
    "effect": "[Activate: Main] [Once Per Turn] DON!! −3 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Place up to 1 of your opponent's Characters with 3000 power or less at the bottom of the owner's deck, and play up to 1 Character card with a cost of 4 or less from your hand.",
    "type": "Heart Pirates",
    "cost": "4",
    "atribbute": "Slash"
  },
  {
    "id": "ST10-002",
    "name": "Monkey.D.Luffy",
    "category": "LEADER",
    "color": "Red/Purple",
    "power": "6000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST10-002.png?240725",
    "effect": "[Activate: Main] [Once Per Turn] If you have 0 DON!! cards on your field or 8 or more DON!! cards on your field, add up to 1 DON!! card from your DON!! deck and set it as active.",
    "type": "Straw Hat Crew",
    "cost": "3",
    "atribbute": "Strike"
  },
  {
    "id": "ST10-003",
    "name": "Eustass\"Captain\"Kid",
    "category": "LEADER",
    "color": "Red/Purple",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST10-003.png?240725",
    "effect": "[Your Turn] If you have 4 or more Life cards, give this Leader −1000 power.[When Attacking] DON!! −1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): This Leader gains +2000 power during this turn.",
    "type": "Kid Pirates",
    "cost": "5",
    "atribbute": "Special"
  },
  {
    "id": "ST12-001",
    "name": "Roronoa Zoro & Sanji",
    "category": "LEADER",
    "color": "Green/Blue",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST12-001.png?240725",
    "effect": "[DON!! x1] [When Attacking] [Once Per Turn] You may return 1 of your Characters with a cost of 2 or more to the owner's hand: Set up to 1 of your Characters with 7000 power or less as active.",
    "type": "Straw Hat Crew",
    "cost": "4",
    "atribbute": "Slash/Strike"
  },
  {
    "id": "ST13-001",
    "name": "Sabo",
    "category": "LEADER",
    "color": "Red/Yellow",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST13-001.png?240725",
    "effect": "[DON!! x1] [Activate: Main] [Once Per Turn] You may add 1 of your Characters with a cost of 3 or more and 7000 power or more to the top of your Life cards face-up: Up to 1 of your Characters gains +2000 power until the start of your next turn.",
    "type": "Dressrosa/Revolutionary Army",
    "cost": "4",
    "atribbute": "Special"
  },
  {
    "id": "ST13-002",
    "name": "Portgas.D.Ace",
    "category": "LEADER",
    "color": "Blue/Yellow",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST13-002.png?240725",
    "effect": "[DON!! x2] [Activate: Main] [Once Per Turn] Look at 5 cards from the top of your deck and add up to 1 Character card with a cost of 5 to the top of your Life cards face-up. Then, place the rest at the bottom of your deck in any order.[End of Your Turn] Trash all your face-up Life cards.",
    "type": "Whitebeard Pirates",
    "cost": "4",
    "atribbute": "Special"
  },
  {
    "id": "ST13-003",
    "name": "Monkey.D.Luffy",
    "category": "LEADER",
    "color": "Black/Yellow",
    "power": "5000",
    "imgURL": "https://en.onepiece-cardgame.com/images/cardlist/card/ST13-003.png?240725",
    "effect": "Your face-up Life cards are placed at the bottom of your deck instead of being added to your hand, according to the rules.[DON!! x2] [Activate: Main] [Once Per Turn] You may trash 1 card from your hand: If you have 0 Life cards, add up to 2 Character cards with a cost of 5 from your hand or trash to the top of your Life cards face-up.",
    "type": "Supernovas/Straw Hat Crew",
    "cost": "4",
    "atribbute": "Strike"
  },
]